# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

byRcpp <- function(nr, frommat, totmat, summat, minmat, maxmat) {
    .Call(`_gjamedit_byRcpp`, nr, frommat, totmat, summat, minmat, maxmat)
}

condMVNRcpp <- function(cdex, gdex, xx, mu, sigma) {
    .Call(`_gjamedit_condMVNRcpp`, cdex, gdex, xx, mu, sigma)
}

tnormRcpp <- function(lo, hi, mu, sig) {
    .Call(`_gjamedit_tnormRcpp`, lo, hi, mu, sig)
}

trMVNmatrixRcpp <- function(avec, muvec, smat, lo, hi, whichSample, idxALL) {
    .Call(`_gjamedit_trMVNmatrixRcpp`, avec, muvec, smat, lo, hi, whichSample, idxALL)
}

rmvnormRcpp <- function(n, mu, sigma) {
    .Call(`_gjamedit_rmvnormRcpp`, n, mu, sigma)
}

solveRcpp <- function(A) {
    .Call(`_gjamedit_solveRcpp`, A)
}

getPmatKRcpp <- function(pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk) {
    .Call(`_gjamedit_getPmatKRcpp`, pveck, Yk, Zk, Xk, Bk, Wk, sigmasqk)
}

fnZRcpp <- function(kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz) {
    .Call(`_gjamedit_fnZRcpp`, kk, Yk, Xk, Dk, Bk, Wk, sigmasqk, Nz)
}

invWbyRcpp <- function(sigsq, A) {
    .Call(`_gjamedit_invWbyRcpp`, sigsq, A)
}

dmvnormRcpp <- function(x, mean, sigma, logd = FALSE) {
    .Call(`_gjamedit_dmvnormRcpp`, x, mean, sigma, logd)
}

randEffRcpp <- function(v, ngvec, sinv, CImat) {
    .Call(`_gjamedit_randEffRcpp`, v, ngvec, sinv, CImat)
}

rcpparma_hello_world <- function() {
    .Call(`_gjamedit_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_gjamedit_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_gjamedit_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_gjamedit_rcpparma_bothproducts`, x)
}

